name: Run K6 Tests

on: [push]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Download and Install K6
        run: |
          K6_VERSION="0.45.1" # Replace with the latest version if needed
          wget https://github.com/grafana/k6/releases/download/v$K6_VERSION/k6-v$K6_VERSION-linux-amd64.tar.gz
          tar -xzf k6-v$K6_VERSION-linux-amd64.tar.gz
          sudo cp k6-v$K6_VERSION-linux-amd64/k6 /usr/local/bin/
          rm -rf k6-v$K6_VERSION-linux-amd64*

      - name: Verify K6 installation
        run: k6 version

      - name: Build project
        run: npm run build

      - name: Run K6 tests
        run: npm run test
